### ISSUE TITLE
TypeError: regex.exec is not a function

### ISSUE THREAD

**Issue by Gergo4961** [pmarkert/async-regex-replace#4]
Hey, ran into this error while trying to edit something using this library:

/var/apps/app/node_modules/async-regex-replace/index.js:22
        var match = regex.exec(str);
                          ^

TypeError: regex.exec is not a function

Any help is appreciated!

**Comment by pmarkert** [comment]
Hello,

  I suspect that your problem is that the first parameter you are passing into the function is not a valid JavaScript regex object. See the README for a usage example. The first parameter should be a regex object, which would have the proper .exec() function available. If that does not resolve your problem, feel free to re-open with a code example included.

**Comment by Gergo4961** [comment]
This is the code I'm using, just for testing purposes:

```
'use strict'

var async_regex_replace = require('async-regex-replace');

var skin='~830 keysUnusual Team Captain Sunbeams';
var regex='(~){1}[0-9.]*( ){1}(keysUnusual ){1}';

async_regex_replace.replace(regex, skin, function(callback, match) {
  setTimeout(function() {
    var replacement_value = match.split('').reverse().join('');
    var err = null;
    callback(err, replacement_value);
  }, 1000);
}, function(err, final_result) {
  if(err) { console.log("Error - " + err); }
  else {
    console.log(final_result);
    //> String with xeger to replace
  }
});
```

I'm not that good with regex so you are right, might be the format of my regex or something, any chance you can help me to fix that? I'm probably missing a few characters to make it properly compatible.
